# Generated by Django 4.1.2 on 2022-10-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('details', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('<8', 'under 8'), ('between', '8-15'), ('>15', 'adults')], max_length=100, null=True)),
                ('total_target', models.FloatField(null=True)),
                ('mult_image', models.ImageField(null=True, upload_to='images')),
                ('Tags', models.CharField(max_length=50)),
                ('sdate', models.DateField(null=True)),
                ('edate', models.DateField(null=True)),
            ],
        ),
    ]
