# Generated by Django 4.1.2 on 2022-10-15 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='avg_rate',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='donate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='rate',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.comment'),
        ),
    ]
