# Generated by Django 4.1.2 on 2022-10-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='donate',
        ),
        migrations.AddField(
            model_name='project',
            name='total_donations',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_target',
            field=models.IntegerField(default=0),
        ),
    ]
