# Generated by Django 4.1.2 on 2022-10-19 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_total_donations_project_donate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.comment'),
        ),
    ]
