# Generated by Django 4.1.2 on 2022-10-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_project_comments_comment_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
