# Generated by Django 4.1.2 on 2022-10-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='total_target',
            field=models.FloatField(default=0),
        ),
    ]
