# Generated by Django 4.1.2 on 2022-10-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_project_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Tags',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.tag'),
        ),
    ]
