# Generated by Django 4.1.2 on 2022-10-31 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_remove_project_mult_image_project_image_projectimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectimage',
            old_name='post',
            new_name='project',
        ),
    ]
