# Generated by Django 4.1.2 on 2022-11-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_rename_post_projectimage_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='name',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
