# Generated by Django 4.1.2 on 2022-11-01 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_categories_alter_project_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='category',
            new_name='categ',
        ),
    ]
