# Generated by Django 4.1.2 on 2022-10-25 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='projects',
        ),
    ]
