# Generated by Django 4.1.2 on 2022-10-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='donations',
            field=models.IntegerField(default=0),
        ),
    ]
